server {
    listen 80;
    server_name my.matrix.com;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name my.matrix.com;

    ssl_certificate /etc/letsencrypt/live/my.matrix.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/my.matrix.com/privkey.pem;

    location /_matrix {
        proxy_pass http://synapse:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        client_max_body_size 500M;
    }

    location /_synapse/admin {
        proxy_pass http://synapse:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://element:80;
    }
}
